package com.elevatorsystemcontrol.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.NotNull;

import java.sql.Timestamp;

@Entity
@Table(name = "elevator_floors")
@NoArgsConstructor
@Data
@AllArgsConstructor
public class ElevatorFloor {

    /**
     * MIN_FLOOR    Define minimum floor available for the elevator
     * MAX_FLOOR    Define maximum floor available for the elevator
     */
    private static final int MIN_FLOOR = -2;
    private static final int MAX_FLOOR = 6;

    @Id
    @Column(name = "id_elevator_floor")
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "elevator_floor_seq")
    @NotNull
    private Long id;

    @Column(name = "floor")
    @Min(MIN_FLOOR)
    @Max(MAX_FLOOR)
    private int floor;


    /**
     * Direction tells if you want to go up or down from the floor you are on
     * 0 - the floor was picked inside the elevator, direction is auto generated by the algorithm
     * 1 - you want to go up
     * 2 - you want to go down
     */
    @Column(name = "direction")
    @Min(0)
    @Max(2)
    private int direction = 0;

    @Column(name = "floor_pick_time")
    private Timestamp floorPickTime;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_elevator")
    @JsonBackReference
    private Elevator elevator;



}
